include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gen.dart'
    - 'build/**'
  
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    missing_required_param: error
    missing_return: error
    avoid_init_to_null: error
    unnecessary_getters_setters: error
    deprecated_member_use: ignore

linter:
  rules:
    always_declare_return_types: error
    always_require_non_null_named_parameters: error
    avoid_dynamic_calls: error
    avoid_void_async: error
    
    always_use_package_imports: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    curly_braces_in_flow_control_structures: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    lines_longer_than_80_chars: true
    
    use_key_in_widget_constructors: true
    prefer_const_constructors_in_immutables: true
    avoid_print: true